<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    //==========================================================================================================================================
    /*
    问：Promise 是怎么运行那些(then、catch、)方法管理的回调【重点💊】
    答：
        1: new 出一个 promise 实例 p
        2: 立即执行同步回调 executer , 
           所以 setTimeout() 就会立即执行,开启一个定时器，开始计时
        3：执行 p.then() 方法
           并且将该方法管理的一组回调 push 进   【promise实例 p 自身的队列里】
           【【fulfilled()=>{}, reason => throw reason】】, 因为该 then 方法没有指定失败的回调
           所以 Promise 内部就会用 reason => throw reason 进行替代
        4：执行 p.catch 方法
          并且将该方法管理的一组回调 push 进队【promise实例 p 自身的队列里】（这组回调只有一个，所以单独成组）
          【【fulfilled()=>{}, reason => throw reason】, 【rejected()=>{}】】
        5: 这时主线程的代码已经执行完毕
           就到 js 的异步任务队列里去拉 setTimeout 执行后指定的 异步回调 【执行该内部的 reject('状态切为-->rejected; ')】
           这时 p 的状态就切换成了 Promise {<rejected>: '状态切为-->rejected; '}
           因为这时的 p 的状态是 rejected ,所以 p.then() 和 p.catch() 所管理的失败的回调就会被【依次】的 push 进异步队列里，
           又因为 p.then()  没有指定失败的回调， 所以【promise 内部就会用 reason => throw reason 进行替代，这个异步函数会被 push 到队列里 】，

           然后按顺序，先从异步队列里拉 then() 所管理的错误回调【reason => throw reason】执行，就会报错【Uncaught (in promise) 状态切为-->rejected; 】
           再从异步队列里拉 catch() 所管理的错误回调进行执行调用，

    */
    const p = new Promise((resolve, reject) => {
      setTimeout(()=>{
        reject('状态切为-->rejected; ')
      },2000)
    })
    p.then(
      ()=>{},
    ) 
    p.catch((reason) => console.log(reason)) // 状态切为-->rejected; 
    const arr = [1,2,3]
    arr.forEach(item => console.log(item))
    //==========================================================================================================================================
    
    
    
  </script>
</body>
</html>